name: Code Quality and Tests

on:
  pull_request:
    branches:
      - main

jobs:
  basic-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run basic pre-commit hooks
        run: |
          pre-commit run trailing-whitespace --all-files
          pre-commit run end-of-file-fixer --all-files
          pre-commit run check-yaml --all-files
          pre-commit run check-added-large-files --all-files
          pre-commit run check-merge-conflict --all-files

  formatting:
    runs-on: ubuntu-latest
    needs: basic-hooks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run formatting tools
        run: |
          pre-commit run black --all-files
          pre-commit run isort --all-files


  setup-and-test:
    runs-on: ubuntu-latest
    needs: formatting
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwertyuiopasdfghjklzxcvbnm
          POSTGRES_DB: swp_hub
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start containers using Docker Compose
      run: docker-compose -f local.yml up --build -d

    - name: Run pytest inside Docker
      run: docker-compose -f local.yml exec web pytest
