name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  basic-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run basic pre-commit hooks
        run: |
          pre-commit run trailing-whitespace --all-files
          pre-commit run end-of-file-fixer --all-files
          pre-commit run check-yaml --all-files
          pre-commit run check-added-large-files --all-files
          pre-commit run check-merge-conflict --all-files
