name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  basic-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run basic pre-commit hooks
        run: pre-commit run --all-files --hook-stage manual --hooks trailing-whitespace,end-of-file-fixer,check-yaml,check-added-large-files,check-merge-conflict

  formatting:
    runs-on: ubuntu-latest
    needs: basic-hooks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run formatting tools
        run: pre-commit run --all-files --hook-stage manual --hooks black,isort

  linting:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run linting tools
        run: pre-commit run --all-files --hook-stage manual --hooks flake8,pylint

  pytest:
    runs-on: ubuntu-latest
    needs: linting  # Optional: make it dependent on linting or remove this line to run independently
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Add other necessary packages here
      - name: Run pytest
        run: pytest
