name: Code Quality and Tests

on:
  pull_request:
    branches:
      - main

jobs:
  basic-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run basic pre-commit hooks
        run: |
          pre-commit run trailing-whitespace --all-files
          pre-commit run end-of-file-fixer --all-files
          pre-commit run check-yaml --all-files
          pre-commit run check-added-large-files --all-files
          pre-commit run check-merge-conflict --all-files

  formatting:
    runs-on: ubuntu-latest
    needs: basic-hooks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run formatting tools
        run: |
          pre-commit run black --all-files
          pre-commit run isort --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Add other necessary packages here
      - name: Run pytest
        run: pytest
