name: Build Images & Tests

on:
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwertyuiopasdfghjklzxcvbnm
          POSTGRES_DB: swp_hub
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start containers using Docker Compose
      run: docker-compose -f local.yml up --build -d

    - name: Run pytest inside Docker
      run: docker-compose -f local.yml exec -T web pytest
